version: '3.8'

services:
  # The Database Layer
  postgres_db:
    image: postgres:15-alpine
    container_name: attendance_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: attendance_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # The Flask Web Server Layer
  web_app:
    build: .
    container_name: attendance_web
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://admin:securepassword123@postgres_db:5432/attendance_db
      - TZ=Asia/Manila # Sets web app timezone
    depends_on:
      - postgres_db
    restart: always
    volumes:
      - .:/app # Mounts local files for real-time development reloading

volumes:
  postgres_data: